version: "3"
services:
  proxy:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./infrastructure/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - nginx_log:/var/log/nginx
      - ./infrastructure/frontend/index.html:/usr/share/nginx/html/index.html
      - ./metadata:/usr/share/nginx/html/metadata
  redis:
    restart: always
    image: redis
    volumes:
      - redis_data:/data
  editor:
    restart: always
    build: ./infrastructure/frontend/editor
    ports:
      - "3000:3000"
    volumes:
      - ./metadata/ui:/metadata
  faas:
    restart: always
    build: ./infrastructure/faas
    volumes:
      - ./metadata/api:/metadata/magic-api
      - faas_log:/opt/log
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MAGIC_USER=${MAGIC_USER}"
      - "MAGIC_PASSWORD=${MAGIC_PASSWORD}"
    depends_on:
      - redis
  mysql:
    restart: always
    build: ./infrastructure/mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${MYSQL_TZ}"
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}"
      - "PMA_HOST=mysql"
      - "PMA_PORT=3306"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - mysql

volumes:
  nginx_log:
    driver: local
  redis_data:
    driver: local
  faas_log:
    driver: local
  mysql_data:
    driver: local