version: "3"
services:
  proxy:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - nginx_log:/var/log/nginx
      - ${HTML_PATH}:/usr/share/nginx/html
  redis:
    restart: always
    image: redis
    volumes:
      - redis_data:/data
  server:
    restart: always
    build: ./server
    volumes:
      - server_log:/opt/log
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - redis
  mysql:
    restart: always
    build: ./mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${MYSQL_TZ}"
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}"
      - "PMA_HOST=mysql"
      - "PMA_PORT=3306"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - mysql
volumes:
  nginx_log:
    driver: local
  redis_data:
    driver: local
  server_log:
    driver: local
  mysql_data:
    driver: local