magic-api:
  web: /api/web
  resource.location: /metadata/magic-api
  security-config:
    username: ${MAGIC_USER:admin}
    password: ${MAGIC_PASSWORD:123456}
  response-code-config:
    success: 0 #执行成功的code值
  response: |- #配置JSON格式，格式为magic-script中的表达式
    {
      code: code,
      status: code,
      message: message,
      msg: message,
      data,
      timestamp,
      requestTime,
      executeTime,
    }

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/default?serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_ROOT_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
logging.file.name: /opt/log/server.log